### ISSUE TITLE
panic at unwrap on first_schema

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#1024]
### What type of bug is this?

Crash

### What subsystems are affected?

Standalone mode

### What happened?

Query:
```sql
select * from demo_memory_usage_bytes limit 1;
``` 

Unwrap hit at https://github.com/GreptimeTeam/greptimedb/blob/develop/src/mito/src/table.rs#L196

Log shows that table `demo_memory_usage_bytes` (id 1024) contains no region:
```rust
        common_telemetry::info!(
            "regions of table {:?}: {:?}",
            self.table_info().name,
            self.regions
        );
```
```
regions of table "demo_api_http_requests_in_progress": {}
```

### What operating system did you use?

macOS 12.3 21E230 arm64

### Relevant log output and stack trace

```bash
at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  72: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.4/src/routing/route.rs:164:61
  73: <F as futures_core::future::TryFuture>::try_poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  74: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  75: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  76: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  77: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  78: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  79: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/future/future.rs:125:9
  80: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  81: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.4/src/routing/route.rs:164:61
  82: <F as futures_core::future::TryFuture>::try_poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  83: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  84: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  85: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  86: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  87: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  88: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/future/future.rs:125:9
  89: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
  90: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.4/src/routing/route.rs:164:61
  91: <tower_http::auth::async_require_authorization::ResponseFuture<Auth,S,ReqBody> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-http-0.3.5/src/auth/async_require_authorization.rs:266:28
  92: <tower_http::trace::future::ResponseFuture<Fut,C,OnResponseT,OnBodyChunkT,OnEosT,OnFailureT> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-http-0.3.5/src/trace/future.rs:52:43
  93: <F as futures_core::future::TryFuture>::try_poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
  94: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
  95: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
  96: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  97: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
  98: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
  99: <F as futures_core::future::TryFuture>::try_poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
 100: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
 101: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
 102: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
 103: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
 104: <tower::util::map_err::MapErrFuture<F,N> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
 105: <F as futures_core::future::TryFuture>::try_poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/future.rs:82:9
 106: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/try_future/into_future.rs:34:9
 107: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/future/future/map.rs:55:37
 108: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
 109: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/lib.rs:91:13
 110: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/macros.rs:38:17
 111: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/future/future.rs:125:9
 112: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.13/src/util/oneshot.rs:97:38
 113: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.4/src/routing/route.rs:164:61
 114: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:491:35
 115: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:297:43
 116: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:161:21
 117: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:137:16
 118: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:120:28
 119: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/proto/h1/dispatch.rs:424:9
 120: <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/server/conn.rs:952:47
 121: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/server/conn.rs:1012:30
 122: <hyper::common::drain::Watching<F,FN> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/common/drain.rs:95:36
 123: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.23/src/server/server.rs:741:36
 124: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
 125: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
 126: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
 127: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
 128: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panic/unwind_safe.rs:271:9
 129: std::panicking::try::do_call
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:483:40
 130: ___rust_try
 131: std::panicking::try
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:447:19
 132: std::panic::catch_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panic.rs:140:14
 133: tokio::runtime::task::harness::poll_future
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
 134: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
 135: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
 136: tokio::runtime::task::raw::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
 137: tokio::runtime::task::raw::RawTask::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
 138: tokio::runtime::task::LocalNotified<S>::run
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:394:9
 139: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
 140: tokio::runtime::coop::with_budget
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
      tokio::runtime::coop::budget
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
 141: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
 142: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
 143: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/scoped_tls.rs:61:9
 144: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
 145: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
 146: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/task.rs:42:21
 147: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
 148: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
 149: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
 150: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
 151: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panic/unwind_safe.rs:271:9
 152: std::panicking::try::do_call
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:483:40
 153: ___rust_try
 154: std::panicking::try
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:447:19
 155: std::panic::catch_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panic.rs:140:14
 156: tokio::runtime::task::harness::poll_future
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
 157: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
 158: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
 159: tokio::runtime::task::raw::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
 160: tokio::runtime::task::raw::RawTask::poll
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
 161: tokio::runtime::task::UnownedTask<S>::run
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:431:9
 162: tokio::runtime::blocking::pool::Task::run
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:159:9
 163: tokio::runtime::blocking::pool::Inner::run
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:511:17
 164: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/u/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:469:13
 165: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/sys_common/backtrace.rs:121:18
 166: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/thread/mod.rs:558:17
 167: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panic/unwind_safe.rs:271:9
 168: std::panicking::try::do_call
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:483:40
 169: ___rust_try
 170: std::panicking::try
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:447:19
 171: std::panic::catch_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panic.rs:140:14
 172: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/thread/mod.rs:557:30
 173: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/ops/function.rs:250:5
 174: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/sys/unix/thread.rs:108:17
 175: __pthread_deallocate
 panic.file="/Users/u/repo/greptimedb-dev/src/mito/src/table.rs" panic.line=196 panic.column=42
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /Users/u/repo/greptimedb-dev/src/mito/src/table.rs:196:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How can we reproduce the bug?

```bash
- Start Prometheus and config remote storage to GreptimeDB. (cargo run -- standalone start)
- Restart after a few minutes (Ctrl-C and cargo run)
- Query (via MySQL client)


DESC TABLE demo_api_http_requests_in_progress works fine. Other tables are ok.
```

**Comment by waynexia** [comment]
It doesn't occur after that. Maybe it's fixed?
