### ISSUE TITLE
Test failure: promql planner::test::count_over_time

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1136]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

After merging #1072, the test `promql planner::test::count_over_time` fails:
```
thread 'planner::test::count_over_time' panicked at 'called `Result::unwrap()` on an `Err` value: DataFusionPlanning { source: SchemaError(FieldNotFound { field: Column { relation: None, name: "timestamp_range" }, valid_fields: [Column { relation: Some("some_metric"), name: "tag_0" }, Column { relation: Some("some_metric"), name: "timestamp" }, Column { relation: Some("some_metric"), name: "field_0" }] }), backtrace: Backtrace(   0: backtrace::backtrace::libunwind::trace
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/capture.rs:140:22
   4: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.4/src/backtrace_shim.rs:15:19
      snafu::GenerateImplicitData::generate_with_source
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.4/src/lib.rs:1152:9
   5: <promql::error::DataFusionPlanningSnafu as snafu::IntoError<promql::error::Error>>::into_error
             at src/error.rs:21:17
   6: <core::result::Result<T,E> as snafu::ResultExt<T,E>>::context
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.4/src/lib.rs:697:31
   7: promql::planner::PromPlanner::prom_expr_to_plan::{{closure}}
             at src/planner.rs:372:17
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/future/future.rs:125:9
   9: promql::planner::PromPlanner::stmt_to_plan::{{closure}}
             at src/planner.rs:105:45
  10: promql::planner::test::indie_query_plan_compare::{{closure}}
             at src/planner.rs:1521:13
  11: promql::planner::test::count_over_time::{{closure}}
             at src/planner.rs:1641:50
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/future/future.rs:125:9
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/future/future.rs:125:9
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:541:57
  15: tokio::runtime::coop::with_budget
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
      tokio::runtime::coop::budget
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
      tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:541:25
  16: tokio::runtime::scheduler::current_thread::Context::enter
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:350:19
  17: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:540:36
  18: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:615:57
  19: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/scoped_tls.rs:61:9
  20: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:615:27
  21: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:530:19
  22: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/current_thread.rs:154:24
  23: tokio::runtime::runtime::Runtime::block_on
             at /Users/dennis/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/runtime.rs:282:47
  24: promql::planner::test::count_over_time
             at src/planner.rs:1641:9
  25: promql::planner::test::count_over_time::{{closure}}
             at src/planner.rs:1628:32
  26: core::ops::function::FnOnce::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/ops/function.rs:250:5
  27: core::ops::function::FnOnce::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/ops/function.rs:250:5
      test::__rust_begin_short_backtrace
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/test/src/lib.rs:656:18
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panic.rs:140:14
      test::run_test_in_process
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/test/src/lib.rs:679:27
      test::run_test::run_test_inner::{{closure}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/test/src/lib.rs:573:39
  29: test::run_test::run_test_inner::{{closure}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/test/src/lib.rs:600:37
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/sys_common/backtrace.rs:121:18
  30: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/thread/mod.rs:560:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panic.rs:140:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/thread/mod.rs:559:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/ops/function.rs:250:5
  31: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/sys/unix/thread.rs:108:17
  32: __pthread_deallocate
) }', src/promql/src/planner.rs:1522:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### What operating system did you use?

Macbook Pro

### How can we reproduce the bug?

```bash
cargo nextest run
```

**Comment by killme2008** [comment]
Reopen when it's fixed.
