### ISSUE TITLE
Cannot run the benchmark

### ISSUE THREAD

**Issue by zamazan4ik** [GreptimeTeam/greptimedb#1201]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

I am trying to run the benchmark, according to the instructions from https://github.com/GreptimeTeam/greptimedb/pull/384 but get an error - `Projected column not found in region`.

I am a newbie to `greptimedb` so hopefully, the fix here should be quite simple.

### What operating system did you use?

macOS Ventura on M1

### Relevant log output and stack trace

```bash
./nyc-taxi --path ~/open_source/greptimedb/dataset/
Create table result: Ok(Output::AffectedRows(0))
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/1
[00:00:00] ------------------------------------------------------------       0/2463931 "/Users/zamazan4ik/open_source/greptimedb/dataset/yellow_tripdata_2022-01.parquet"              thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', benchmarks/src/bin/nyc-taxi.rs:167:18
Running query: SELECT COUNT(*) FROM nyc_taxi;
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FlightGet { addr: "127.0.0.1:3001", tonic_code: Internal, source: Projected column not found in region, column: nyc_taxi.0_0000000000.VendorID. }', benchmarks/src/bin/nyc-taxi.rs:404:45
```
```


### How can we reproduce the bug?

```bash
Follow the instructions from https://github.com/GreptimeTeam/greptimedb/pull/384 on the latest `greptimedb` from the `develop` branch.
```

**Comment by waynexia** [comment]
Sorry for the inconvenience, I've submitted a fix in #1204.

BTW, this is caused by the wrong `table_id` in `CreateTableExpr` request.
