### ISSUE TITLE
Test failure: frontend tests::instance_test::test_execute_copy_to_s3

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1301]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Frontend

### What happened?

As seen in https://github.com/GreptimeTeam/greptimedb/actions/runs/4582437037/jobs/8092674711

```
--- STDERR:              frontend tests::instance_test::test_execute_copy_from_s3 ---
thread 'tests::instance_test::test_execute_copy_from_s3' panicked at 'called `Result::unwrap()` on an `Err` value: ExecuteStatement { source: QueryExecution { source: Failed to list objects, source: Failed to list object in path: /21a84a69-7476-4bac-85ff-da40b389881e/export/demo.parquet_1_2, source: NotFound (permanent) at stat, context: { response: Parts { status: 404, version: HTTP/1.1, headers: {"x-amz-request-id": "7FRSB0HT74G0RYBK", "x-amz-id-2": "7d8JoauraI8+ckszrc7zTK6ZOxgAeCIAzz86q8amMnCp2MOCTa65SphWzPd+CTtLZf7jSEhZIHc=", "content-type": "application/xml", "date": "Sat, 01 Apr 2023 09:32:52 GMT", "server": "AmazonS3"} }, service: s3, path: 21a84a69-7476-4bac-85ff-da40b389881e/export/demo.parquet_1_2 }. Caused by: ListObjects { path: "/21a84a69-7476-4bac-85ff-da40b389881e/export/demo.parquet_1_2", backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/snafu-0.7.4/src/backtrace_shim.rs:15:19
      <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate_with_source
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/snafu-0.7.4/src/lib.rs:1152:9
   1: <common_datasource::error::ListObjectsSnafu<&alloc::string::String> as snafu::IntoError<common_datasource::error::Error>>::into_error
             at /home/runner/work/greptimedb/greptimedb/src/common/datasource/src/error.rs:20:17
   2: <core::result::Result<opendal::types::metadata::Metadata, opendal::types::error::Error> as snafu::ResultExt<opendal::types::metadata::Metadata, opendal::types::error::Error>>::context::<common_datasource::error::ListObjectsSnafu<&alloc::string::String>, common_datasource::error::Error>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/snafu-0.7.4/src/lib.rs:697:31
   3: <common_datasource::lister::Lister>::list::{closure#0}
             at /home/runner/work/greptimedb/greptimedb/src/common/datasource/src/lister.rs:74:25
   4: <datanode::sql::SqlHandler>::copy_table_from::{closure#0}
             at /home/runner/work/greptimedb/greptimedb/src/datanode/src/sql/copy_table_from.rs:66:36
   5: <datanode::sql::SqlHandler>::execute::{closure#0}
             at /home/runner/work/greptimedb/greptimedb/src/datanode/src/sql.rs:89:67
   6: <datanode::instance::Instance>::execute_stmt::{closure#0}
             at /home/runner/work/greptimedb/greptimedb/src/datanode/src/instance/sql.rs:176:21
   7: <datanode::instance::Instance as query::query_engine::StatementHandler>::handle_statement::{closure#0}
             at /home/runner/work/greptimedb/greptimedb/src/datanode/src/instance/sql.rs:288:13
   8: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<common_query::Output, query::error::Error>> + core::marker::Send>> as core::future::future::Future>::poll
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/future/future.rs:125:9
   9: <frontend::instance::Instance>::query_statement::{closure#0}
             at src/instance.rs:519:17
  10: <frontend::instance::Instance as servers::query_handler::sql::SqlQueryHandler>::do_query::{closure#0}
             at src/instance.rs:556:72
  11: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = alloc::vec::Vec<core::result::Result<common_query::Output, frontend::error::Error>>> + core::marker::Send>> as core::future::future::Future>::poll
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/future/future.rs:125:9
  12: frontend::tests::instance_test::try_execute_sql_in_db::{closure#0}
             at src/tests/instance_test.rs:925:47
  13: frontend::tests::instance_test::execute_sql_in_db::{closure#0}
             at src/tests/instance_test.rs:929:45
  14: frontend::tests::instance_test::execute_sql::{closure#0}
             at src/tests/instance_test.rs:909:58
  15: frontend::tests::instance_test::test_execute_copy_from_s3::{closure#0}
             at src/tests/instance_test.rs:886:58
  16: <core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>> as core::future::future::Future>::poll
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/future/future.rs:125:9
  17: <tokio::runtime::park::CachedParkThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:63
  18: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>::{closure#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>::{closure#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
      <tokio::runtime::park::CachedParkThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:31
  19: <tokio::runtime::context::BlockingRegionGuard>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/context.rs:315:13
  20: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  21: <tokio::runtime::runtime::Runtime>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/runtime.rs:304:45
  22: frontend::tests::instance_test::test_execute_copy_from_s3
             at src/tests/instance_test.rs:811:5
  23: frontend::tests::instance_test::test_execute_copy_from_s3::{closure#0}
             at src/tests/instance_test.rs:809:38
  24: <frontend::tests::instance_test::test_execute_copy_from_s3::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/ops/function.rs:250:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/ops/function.rs:250:5
      test::__rust_begin_short_backtrace
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/test/src/lib.rs:656:18
  26: test::run_test::{{closure}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/test/src/lib.rs:647:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/ops/function.rs:250:5
  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panic.rs:140:14
      test::run_test_in_process
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/test/src/lib.rs:679:27
      test::run_test::run_test_inner::{{closure}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/test/src/lib.rs:573:39
  28: test::run_test::run_test_inner::{{closure}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/test/src/lib.rs:600:37
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/sys_common/backtrace.rs:121:18
  29: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/thread/mod.rs:560:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:487:40
      std::panicking::try
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:451:19
      std::panic::catch_unwind
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panic.rs:140:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/thread/mod.rs:559:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/ops/function.rs:250:5
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/sys/unix/thread.rs:108:17
  31: <unknown>
  32: <unknown>
), source: NotFound (permanent) at stat

Context:
    response: Parts { status: 404, version: HTTP/1.1, headers: {"x-amz-request-id": "7FRSB0HT74G0RYBK", "x-amz-id-2": "7d8JoauraI8+ckszrc7zTK6ZOxgAeCIAzz86q8amMnCp2MOCTa65SphWzPd+CTtLZf7jSEhZIHc=", "content-type": "application/xml", "date": "Sat, 01 Apr 2023 09:32:52 GMT", "server": "AmazonS3"} }
    service: s3
    path: 21a84a69-7476-4bac-85ff-da40b389881e/export/demo.parquet_1_2
 }
```

### What operating system did you use?

ubuntu

### How can we reproduce the bug?

```bash
https://github.com/GreptimeTeam/greptimedb/actions/runs/4582437037/jobs/8092674711
```

**Comment by v0y4g3r** [comment]
It's related to #1263. `COPY TO` now exports table rows into a single file instead of many chunks, so there will not be a `demo.parquet_1_2` file any more. I adapted the sqlness test but didn't find there's a s3 test depends on this convention.
