### ISSUE TITLE
Please update substrait to the latest version

### ISSUE THREAD

**Issue by yurivict** [GreptimeTeam/greptimedb#1366]
### What type of bug is this?

Other

### What subsystems are affected?

Other

### What happened?

Build failure.

### What operating system did you use?

FreeBSD 13.1

### Relevant log output and stack trace

```bash
Build breaks:

     Running `CARGO=/usr/local/bin/cargo CARGO_CRATE_NAME=lz4 CARGO_MANIFEST_DIR=/usr/ports/databases/greptimedb/work/greptimedb-0.2.0-nightly-20230410-8-ga90798a2/cargo-crates/lz4-1.24.0 CARGO_PKG_AUTHORS='Jens Heyens <jens.heyens@ewetel.net>:Artem V. Navrotskiy <bozaro@buzzsoft.ru>:Patrick Marks <pmarks@gmail.com>' CARGO_PKG_DESCRIPTION='Rust LZ4 bindings library.' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=lz4 CARGO_PKG_REPOSITORY='https://github.com/10xGenomics/lz4-rs' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=1.24.0 CARGO_PKG_VERSION_MAJOR=1 CARGO_PKG_VERSION_MINOR=24 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/usr/ports/databases/greptimedb/work/target/release/deps:/usr/local/lib' /usr/local/bin/rustc --crate-name lz4 --edition=2018 /usr/ports/databases/greptimedb/work/greptimedb-0.2.0-nightly-20230410-8-ga90798a2/cargo-crates/lz4-1.24.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=201 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 -C metadata=303ac3ef8d5d58b7 -C extra-filename=-303ac3ef8d5d58b7 --out-dir /usr/ports/databases/greptimedb/work/target/x86_64-unknown-freebsd/release/deps --target x86_64-unknown-freebsd -C linker=cc -L dependency=/usr/ports/databases/greptimedb/work/target/x86_64-unknown-freebsd/release/deps -L dependency=/usr/ports/databases/greptimedb/work/target/release/deps --extern libc=/usr/ports/databases/greptimedb/work/target/x86_64-unknown-freebsd/release/deps/liblibc-44dea1ff84b9dc28.rmeta --extern lz4_sys=/usr/ports/databases/greptimedb/work/target/x86_64-unknown-freebsd/release/deps/liblz4_sys-422ca0308c219cdf.rmeta --cap-lints warn -C link-arg=-fstack-protector-strong -L native=/usr/ports/databases/greptimedb/work/target/x86_64-unknown-freebsd/release/build/lz4-sys-fd6ed9925cc3c683/out`
[substrait 0.4.2] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoRustfmt', /usr/ports/databases/greptimedb/work/greptimedb-0.2.0-nightly-20230410-8-ga90798a2/cargo-crates/typify-impl-0.0.10/src/lib.rs:614:47
[substrait 0.4.2] stack backtrace:
[substrait 0.4.2]    0: rust_begin_unwind
[substrait 0.4.2]    1: core::panicking::panic_fmt
[substrait 0.4.2]    2: core::result::unwrap_failed
[substrait 0.4.2]    3: core::result::Result<T,E>::unwrap
[substrait 0.4.2]              at /wrkdirs/usr/ports/lang/rust/work/rustc-1.68.2-src/library/core/src/result.rs:1112:23
[substrait 0.4.2]    4: <typify_impl::TypeSpace as alloc::string::ToString>::to_string
[substrait 0.4.2]              at /usr/ports/databases/greptimedb/work/greptimedb-0.2.0-nightly-20230410-8-ga90798a2/cargo-crates/typify-impl-0.0.10/src/lib.rs:614:9
[substrait 0.4.2]    5: build_script_build::text
[substrait 0.4.2]              at ./build.rs:74:13
[substrait 0.4.2]    6: build_script_build::main
[substrait 0.4.2]              at ./build.rs:151:5
[substrait 0.4.2]    7: core::ops::function::FnOnce::call_once
[substrait 0.4.2]              at /wrkdirs/usr/ports/lang/rust/work/rustc-1.68.2-src/library/core/src/ops/function.rs:250:5
[substrait 0.4.2] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `substrait v0.4.2`
```

Old versions of substrait break without rustfmt.
```


### How can we reproduce the bug?

```bash
Regular build.
```

**Comment by WenyXu** [comment]
Hi, Thank you for reporting. I guess it's the same problem in #1358, where the version `protobuf` earlier than 3.15 will yield a build error. Which version of `protobuf` are you using? 
See also https://grpc.io/docs/protoc-installation/

**Comment by waynexia** [comment]
And the upgrade is in progress at https://github.com/GreptimeTeam/greptimedb/pull/1238. It's likely to be done this or early next week

**Comment by waynexia** [comment]
Hi @yurivict, we've updated the substrait to 0.7, could you please give it a try 🤗

**Comment by yurivict** [comment]
The original error is gone. But now it fails like this:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/table/src/lib.rs:14:12
   | 
14 | #![feature(assert_matches)]
   |            ^^^^^^^^^^^^^^
```

I use rust-1.68.2. Is it now new enough?

**Comment by evenyag** [comment]
You need to use rust-nightly. This feature is only available on nightly rust.

**Comment by killme2008** [comment]
Already upgrade to the latest substrate. I closed this issue, feel free to reopen it when you are still in trouble.
