### ISSUE TITLE
test: test_region_manifest_checkpoint fails occasionally

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#1490]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Standalone mode, Datanode

### What happened?

Test failure:
```
thread 'manifest::region::tests::test_region_manifest_checkpoint' panicked at 'assertion failed: manifest.scan(0,\n                            MAX_VERSION).await.unwrap().next_action().await.unwrap().is_none()', src/storage/src/manifest/region.rs:368:9
```

### What operating system did you use?

All

### Relevant log output and stack trace

```bash
--- STDOUT:              storage manifest::region::tests::test_region_manifest_checkpoint ---

running 1 test
2023-04-27T08:24:13.554037Z  INFO common_telemetry::logging: logs dir = /tmp/__unittest_logs
2023-04-27T08:24:13.582251Z DEBUG opendal::services::fs::backend: backend build started: FsBuilder { root: Some("/var/folders/0g/nq9zjrj92rx8h465llxn9qch0000gn/T/test_region_manifest_checkpointVq6VhJ"), atomic_write_dir: None, enable_path_check: false }
2023-04-27T08:24:13.582378Z DEBUG opendal::services::fs::backend: backend use root /var/folders/0g/nq9zjrj92rx8h465llxn9qch0000gn/T/test_region_manifest_checkpointVq6VhJ
2023-04-27T08:24:13.582476Z DEBUG opendal::services::fs::backend: backend build finished: FsBuilder { root: None, atomic_write_dir: None, enable_path_check: false }
2023-04-27T08:24:13.582624Z  INFO common_runtime::global: Creating runtime, thread name: read-worker, work_threads: 8.
2023-04-27T08:24:13.582849Z  INFO common_runtime::global: Creating runtime, thread name: write-worker, work_threads: 8.
2023-04-27T08:24:13.583030Z  INFO common_runtime::global: Creating runtime, thread name: bg-worker, work_threads: 8.
2023-04-27T08:24:13.583235Z DEBUG common_runtime::repeated_task: Repeated task region-manifest-gc started with interval: 50ms
2023-04-27T08:24:13.583735Z  INFO storage::manifest::impl_: Updated manifest protocol from Protocol(0, 0) to Protocol(0, 0).
2023-04-27T08:24:13.583772Z DEBUG storage::manifest::impl_: Save region metadata action: RegionMetaActionList { actions: [Protocol(ProtocolAction { min_reader_version: 0, min_writer_version: 0 }), Change(RegionChange { committed_sequence: 1, metadata: RawRegionMetadata { id: 0, name: "region-0", columns: RawColumnsMetadata { columns: [ColumnMetadata { cf_id: 0, desc: ColumnDescriptor { id: 2, name: "k1", data_type: Int32(Int32Type), is_nullable: false, is_time_index: false, default_constraint: None, comment: "" } }, ColumnMetadata { cf_id: 0, desc: ColumnDescriptor { id: 1, name: "timestamp", data_type: Timestamp(Millisecond(TimestampMillisecondType)), is_nullable: false, is_time_index: true, default_constraint: None, comment: "" } }, ColumnMetadata { cf_id: 1, desc: ColumnDescriptor { id: 3, name: "v1", data_type: Float32(Float32Type), is_nullable: true, is_time_index: false, default_constraint: None, comment: "" } }, ColumnMetadata { cf_id: 1, desc: ColumnDescriptor { id: 2147483649, name: "__sequence", data_type: UInt64(UInt64Type), is_nullable: false, is_time_index: false, default_constraint: None, comment: "" } }, ColumnMetadata { cf_id: 1, desc: ColumnDescriptor { id: 2147483650, name: "__op_type", data_type: UInt8(UInt8Type), is_nullable: false, is_time_index: false, default_constraint: None, comment: "" } }], row_key_end: 2, timestamp_key_index: 1, enable_version_column: false, user_column_end: 3 }, column_families: RawColumnFamiliesMetadata { column_families: [ColumnFamilyMetadata { name: "default", cf_id: 1, column_index_start: 2, column_index_end: 3 }] }, version: 0, compaction_time_window: None } })], prev_version: 0 }, version: 0
2023-04-27T08:24:13.642100Z DEBUG storage::manifest::impl_: Save region metadata action: RegionMetaActionList { actions: [Edit(RegionEdit { region_version: 0, flushed_sequence: Some(2), files_to_add: [FileMeta { region_id: 0, file_id: FileId(dc4e03f0-96ad-4bae-a32a-d89035836308), time_range: None, level: 0, file_size: 1024 }], files_to_remove: [] }), Edit(RegionEdit { region_version: 0, flushed_sequence: Some(3), files_to_add: [FileMeta { region_id: 0, file_id: FileId(f797a9d8-75ff-4855-8f06-74cc7a97f16d), time_range: None, level: 0, file_size: 1024 }, FileMeta { region_id: 0, file_id: FileId(f4e062c7-9b46-4bbc-bc88-0d58d0220071), time_range: None, level: 0, file_size: 1024 }], files_to_remove: [FileMeta { region_id: 0, file_id: FileId(dc4e03f0-96ad-4bae-a32a-d89035836308), time_range: None, level: 0, file_size: 1024 }] })], prev_version: 0 }, version: 1
2023-04-27T08:24:13.713522Z DEBUG storage::manifest::impl_: Save region metadata action: RegionMetaActionList { actions: [Change(RegionChange { committed_sequence: 99, metadata: RawRegionMetadata { id: 0, name: "region-0", columns: RawColumnsMetadata { columns: [ColumnMetadata { cf_id: 0, desc: ColumnDescriptor { id: 2, name: "k1", data_type: Int32(Int32Type), is_nullable: false, is_time_index: false, default_constraint: None, comment: "" } }, ColumnMetadata { cf_id: 0, desc: ColumnDescriptor { id: 1, name: "timestamp", data_type: Timestamp(Millisecond(TimestampMillisecondType)), is_nullable: false, is_time_index: true, default_constraint: None, comment: "" } }, ColumnMetadata { cf_id: 1, desc: ColumnDescriptor { id: 3, name: "v1", data_type: Float32(Float32Type), is_nullable: true, is_time_index: false, default_constraint: None, comment: "" } }, ColumnMetadata { cf_id: 1, desc: ColumnDescriptor { id: 4, name: "v2", data_type: Float32(Float32Type), is_nullable: true, is_time_index: false, default_constraint: None, comment: "" } }, ColumnMetadata { cf_id: 1, desc: ColumnDescriptor { id: 2147483649, name: "__sequence", data_type: UInt64(UInt64Type), is_nullable: false, is_time_index: false, default_constraint: None, comment: "" } }, ColumnMetadata { cf_id: 1, desc: ColumnDescriptor { id: 2147483650, name: "__op_type", data_type: UInt8(UInt8Type), is_nullable: false, is_time_index: false, default_constraint: None, comment: "" } }], row_key_end: 2, timestamp_key_index: 1, enable_version_column: false, user_column_end: 4 }, column_families: RawColumnFamiliesMetadata { column_families: [ColumnFamilyMetadata { name: "default", cf_id: 1, column_index_start: 2, column_index_end: 4 }] }, version: 0, compaction_time_window: None } })], prev_version: 0 }, version: 2
2023-04-27T08:24:13.910207Z DEBUG storage::manifest::storage: Save checkpoint in path: /manifest/_last_checkpoint,  metadata: CheckpointMetadata { size: 1747, version: 2, checksum: None, extend_metadata: None }
2023-04-27T08:24:13.967133Z DEBUG storage::manifest::storage: Load checkpoint in path: /manifest/_last_checkpoint, metadata: CheckpointMetadata { size: 1747, version: 2, checksum: None, extend_metadata: None }
2023-04-27T08:24:13.968586Z DEBUG storage::manifest::storage: Deleting 2 logs from manifest storage path /manifest/.
2023-04-27T08:24:14.020325Z DEBUG storage::manifest::impl_: Deleted 2 logs from region manifest storage(path=/manifest/).
2023-04-27T08:24:14.021045Z ERROR storage::manifest::region: Failed to delete manifest logs [0,2] in path: /manifest/. err.msg=Fail to delete object from path: /manifest/00000000000000000000.json,/manifest/00000000000000000001.json,/manifest/00000000000000000002.json, source: NotFound (permanent) at delete, context: { service: fs, path: manifest/00000000000000000000.json } => entity not found, source: No such file or directory (os error 2) err.code=StorageUnavailable err.source=NotFound (permanent) at delete, context: { service: fs, path: manifest/00000000000000000000.json } => entity not found, source: No such file or directory (os error 2) err.source.sources=[No such file or directory (os error 2)]
2023-04-27T08:24:14.021210Z  INFO storage::manifest::region: Region manifest checkpoint, start_version: 0, last_version: 2, compacted actions: 3
2023-04-27T08:24:14.021559Z DEBUG storage::manifest::storage: Load checkpoint in path: /manifest/_last_checkpoint, metadata: CheckpointMetadata { size: 1747, version: 2, checksum: None, extend_metadata: None }
2023-04-27T08:24:14.073093Z DEBUG storage::manifest::storage: Load checkpoint in path: /manifest/_last_checkpoint, metadata: CheckpointMetadata { size: 1747, version: 2, checksum: None, extend_metadata: None }
2023-04-27T08:24:14.073688Z DEBUG storage::manifest::storage: Deleting 0 logs from manifest storage path /manifest/.
2023-04-27T08:24:14.073756Z DEBUG storage::manifest::impl_: Deleted 0 logs from region manifest storage(path=/manifest/).
test manifest::region::tests::test_region_manifest_checkpoint ... FAILED

failures:

failures:
    manifest::region::tests::test_region_manifest_checkpoint

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 144 filtered out; finished in 0.57s


--- STDERR:              storage manifest::region::tests::test_region_manifest_checkpoint ---
thread 'manifest::region::tests::test_region_manifest_checkpoint' panicked at 'assertion failed: manifest.scan(0,\n                            MAX_VERSION).await.unwrap().next_action().await.unwrap().is_none()', src/storage/src/manifest/region.rs:368:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/panicking.rs:114:5
   3: storage::manifest::region::tests::test_region_manifest_checkpoint::{{closure}}
             at ./src/manifest/region.rs:368:9
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/34e6673a0473e90ef01a18eb575392c9e3859747/library/core/src/future/future.rs:125:9
```

### How can we reproduce the bug?

run unit tests

**Comment by evenyag** [comment]
After some investigation, I find out the root cause is the GC task doesn't remove the last file:

https://github.com/GreptimeTeam/greptimedb/blob/47f1cbaaed8e5c95a1e867627d5ffc1519d39883/src/storage/src/manifest/impl_.rs#L252-L261

It removes files until (less than) last_version. However, we should also remove the file of the last version like this:
https://github.com/GreptimeTeam/greptimedb/blob/47f1cbaaed8e5c95a1e867627d5ffc1519d39883/src/storage/src/manifest/region.rs#L119-L129

If the GC task ran before and deleted files less than last_version, then the manifest store is unable to remove files from 0 to last_version.
```rust
2023-04-27T08:24:14.021045Z ERROR storage::manifest::region: Failed to delete manifest logs [0,2] in path: /manifest/. err.msg=Fail to delete object from path: /manifest/00000000000000000000.json,/manifest/00000000000000000001.json,/manifest/00000000000000000002.json, source: NotFound (permanent) at delete, context: { service: fs, path: manifest/00000000000000000000.json } => entity not found, source: No such file or directory (os error 2) err.code=StorageUnavailable err.source=NotFound (permanent) at delete, context: { service: fs, path: manifest/00000000000000000000.json } => entity not found, source: No such file or directory (os error 2) err.source.sources=[No such file or directory (os error 2)]
```

**Comment by evenyag** [comment]
Just for a reminder for me:
```
2023-04-27T08:24:14.020325Z DEBUG storage::manifest::impl_: Deleted 2 logs from region manifest storage(path=/manifest/).
2023-04-27T08:24:14.021045Z ERROR storage::manifest::region: Failed to delete manifest logs [0,2] in path: /manifest/. err.msg=Fail to delete object from path: /manifest/00000000000000000000.json,/manifest/00000000000000000001.json,/manifest/00000000000000000002.json, source: NotFound (permanent) at delete, context: { service: fs, path: manifest/00000000000000000000.json } => entity not found, source: No such file or directory (os error 2) err.code=StorageUnavailable err.source=NotFound (permanent) at delete, context: { service: fs, path: manifest/00000000000000000000.json } => entity not found, source: No such file or directory (os error 2) err.source.sources=[No such file or directory (os error 2)]
2023-04-27T08:24:14.021210Z  INFO storage::manifest::region: Region manifest checkpoint, start_version: 0, last_version: 2, compacted actions: 3
2023-04-27T08:24:14.021559Z DEBUG storage::manifest::storage: Load checkpoint in path: /manifest/_last_checkpoint, metadata: CheckpointMetadata { size: 1747, version: 2, checksum: None, extend_metadata: None }
2023-04-27T08:24:14.073093Z DEBUG storage::manifest::storage: Load checkpoint in path: /manifest/_last_checkpoint, metadata: CheckpointMetadata { size: 1747, version: 2, checksum: None, extend_metadata: None }
2023-04-27T08:24:14.073688Z DEBUG storage::manifest::storage: Deleting 0 logs from manifest storage path /manifest/.
2023-04-27T08:24:14.073756Z DEBUG storage::manifest::impl_: Deleted 0 logs from region manifest storage(path=/manifest/).
``

OpenDAL might return an error if path in remove() doesn't exist
