### ISSUE TITLE
Region tests fail because of logstore's file lock

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#1772]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

Some region related unit tests fail because raft-engine instance is not dropped after region closed, so the reopened raft-engine instance will panick when fail to acquire file lock.

### What operating system did you use?

NA

### Relevant log output and stack trace

```bash
unning 1 test
test region::tests::flush::test_merge_read_after_flush ... FAILED

failures:

failures:
    region::tests::flush::test_merge_read_after_flush

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 173 filtered out; finished in 1.54s


--- STDERR:              storage region::tests::flush::test_merge_read_after_flush ---
thread 'region::tests::flush::test_merge_read_after_flush' panicked at 'called `Result::unwrap()` on an `Err` value: RaftEngine { source: Other("[/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/raft-engine-0.3.0/src/file_pipe_log/pipe_builder.rs:439]: Failed to lock file: Resource temporarily unavailable (os error 11), maybe another instance is using this directory."), location: Location { file: "/home/runner/work/greptimedb/greptimedb/src/log-store/src/raft_engine/log_store.rs", line: 97, column: 64 } }', src/storage/src/test_util/config_util.rs:97:76
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/result.rs:1651:5
   3: <core::result::Result<log_store::raft_engine::log_store::RaftEngineLogStore, log_store::error::Error>>::unwrap
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/result.rs:1076:23
   4: storage::test_util::config_util::new_store_config_with_object_store::{closure#0}
             at ./src/test_util/config_util.rs:97:30
   5: storage::test_util::config_util::new_store_config::{closure#0}
             at ./src/test_util/config_util.rs:50:10
   6: <storage::region::tests::flush::FlushTester>::reopen::{closure#0}
             at ./src/region/tests/flush.rs:104:10
   7: storage::region::tests::flush::test_merge_read_after_flush::{closure#0}
             at ./src/region/tests/flush.rs:334:21
   8: <core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>> as core::future::future::Future>::poll
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/future/future.rs:125:9
   9: <core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/future/future.rs:125:9
  10: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:541:57
  11: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
  12: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
  13: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:541:25
  14: <tokio::runtime::scheduler::current_thread::Context>::enter::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:350:19
  15: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:540:36
  16: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, core::option::Option<()>>::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:615:57
  17: <tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::current_thread::Context>>::set::<<tokio::runtime::scheduler::current_thread::CoreGuard>::enter<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, core::option::Option<()>>::{closure#0}, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core>, core::option::Option<()>)>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
  18: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, core::option::Option<()>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:615:27
  19: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:530:19
  20: <tokio::runtime::scheduler::current_thread::CurrentThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/current_thread.rs:154:24
  21: <tokio::runtime::runtime::Runtime>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/runtime.rs:302:47
  22: storage::region::tests::flush::test_merge_read_after_flush
             at ./src/region/tests/flush.rs:338:5
  23: storage::region::tests::flush::test_merge_read_after_flush::{closure#0}
             at ./src/region/tests/flush.rs:296:40
  24: <storage::region::tests::flush::test_merge_read_after_flush::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/ops/function.rs:250:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

   Canceling due to test failure: 5 tests still running
        PASS [   0.019s] table metadata::tests::test_remove_multiple_columns_before_timestamp
        PASS [   0.027s] table metadata::tests::test_remove_columns
        PASS [   0.022s] table metadata::tests::test_remove_unknown_column
        PASS [   0.032s] table metadata::tests::test_remove_key_column
        PASS [   0.079s] table predicate::tests::test_prune_all_match
        PASS [   0.079s] table predicate::tests::test_prune_between_expr
        PASS [   0.085s] table predicate::tests::test_or
        PASS [   7.659s] servers::mod mysql::mysql_server_test::test_query_concurrently
------------
     Summary [  21.173s] 1291/1442 tests run: 1290 passed, 1 failed, 5 skipped
        FAIL [   1.613s] storage region::tests::flush::test_merge_read_after_flush
```

### How can we reproduce the bug?

Run unit tests in Github CI workflow.

**Comment by v0y4g3r** [comment]
It turned out to be that spawned flush task still held a reference to `WAL` while region was reopening. 

We need to find a way to wait for all pending flush tasks to finishe.

Fixed by #1767.
