### ISSUE TITLE
Test failure: storage scheduler::tests::test_await_termination

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#1788]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

Failed in action https://github.com/GreptimeTeam/greptimedb/actions/runs/5309107020/jobs/9609411511?pr=1776

```text
--- STDERR:              storage scheduler::tests::test_await_termination ---
thread 'scheduler::tests::test_await_termination' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', src/storage/src/scheduler.rs:582:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<i32, i32>
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/panicking.rs:228:5
   4: storage::scheduler::tests::test_await_termination::{closure#0}
             at ./src/scheduler.rs:582:9
   5: <core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>> as core::future::future::Future>::poll
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/future/future.rs:125:9
   6: <core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/future/future.rs:125:9
   7: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:541:57
   8: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  10: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:541:25
  11: <tokio::runtime::scheduler::current_thread::Context>::enter::<core::task::poll::Poll<()>, <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}::{closure#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:350:19
  12: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:540:36
  13: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, core::option::Option<()>>::{closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:615:57
  14: <tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::current_thread::Context>>::set::<<tokio::runtime::scheduler::current_thread::CoreGuard>::enter<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, core::option::Option<()>>::{closure#0}, (alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core>, core::option::Option<()>)>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  15: <tokio::runtime::scheduler::current_thread::CoreGuard>::enter::<<tokio::runtime::scheduler::current_thread::CoreGuard>::block_on<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, core::option::Option<()>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:615:27
  16: <tokio::runtime::scheduler::current_thread::CoreGuard>::block_on::<core::pin::Pin<&mut core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:530:19
  17: <tokio::runtime::scheduler::current_thread::CurrentThread>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba[1500](https://github.com/GreptimeTeam/greptimedb/actions/runs/5309107020/jobs/9609411511?pr=1776#step:11:1501)1f/tokio-1.28.2/src/runtime/scheduler/current_thread.rs:154:24
  18: <tokio::runtime::runtime::Runtime>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/runtime.rs:302:47
  19: storage::scheduler::tests::test_await_termination
             at ./src/scheduler.rs:582:9
  20: storage::scheduler::tests::test_await_termination::{closure#0}
             at ./src/scheduler.rs:548:39
  21: <storage::scheduler::tests::test_await_termination::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/ops/function.rs:250:5
  22: core::ops::function::FnOnce::call_once
             at /rustc/a368898de758e1b8def6c9060044a5b40eb79e84/library/core/src/ops/function.rs:250:5
```

### What operating system did you use?

Ubuntu

### How can we reproduce the bug?

Under rare conditions.

**Comment by evenyag** [comment]
This test doesn't wait the background task before checking scheduled task num
https://github.com/GreptimeTeam/greptimedb/blob/d1b5ce0d35203789536a703854d02b7d6cfdff27/src/storage/src/scheduler.rs#L567-L582

I'll open a PR to fix it.
