### ISSUE TITLE
500 error when using PromQL with time durations

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/greptimedb#2350]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Frontend

### What happened?

Adding time duration in PromQL will occur an error, for example `node_cpu_seconds_total{mode="idle"}[5m]`.

```
curl -X GET \
-H 'Authorization: Basic <authorization>' \
-G \
--data-urlencode 'db=qg4xuulda0aaprometheus_machine_metrics-public' \
--data-urlencode 'query=node_cpu_seconds_total{mode="idle"}[5m]' \
--data-urlencode 'start=1694419256' \
--data-urlencode 'end=1694419856' \
--data-urlencode 'step=15s' \
https://o3aw21qgdbzw.us-west-2.aws.greptime.cloud/v1/promql
```

The response is
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

If starting a db locally, the error is:

```
greptimedb           | not implemented: Arrow array datatype: Dictionary(Int64, Float64)
greptimedb           | 2023-09-11T08:25:36.318939Z ERROR common_telemetry::panic_hook: panicked at /greptimedb/src/datatypes/src/vectors/helper.rs:323:17:
greptimedb           | not implemented: Arrow array datatype: Dictionary(Int64, Float64) backtrace=   0: <unknown>
greptimedb           |    1: <unknown>
greptimedb           |    2: <unknown>
greptimedb           |    3: <unknown>
greptimedb           |    4: <unknown>
greptimedb           |    5: <unknown>
greptimedb           |    6: <unknown>
greptimedb           |    7: <unknown>
greptimedb           |    8: <unknown>
greptimedb           |    9: <unknown>
greptimedb           |   10: <unknown>
greptimedb           |   11: <unknown>
greptimedb           |   12: <unknown>
greptimedb           |   13: <unknown>
greptimedb           |   14: <unknown>
greptimedb           |   15: <unknown>
greptimedb           |   16: <unknown>
greptimedb           |   17: <unknown>
greptimedb           |   18: <unknown>
greptimedb           |   19: <unknown>
greptimedb           |   20: <unknown>
greptimedb           |   21: <unknown>
greptimedb           |   22: <unknown>
greptimedb           |   23: <unknown>
greptimedb           |   24: <unknown>
greptimedb           |   25: <unknown>
greptimedb           |   26: <unknown>
greptimedb           |   27: <unknown>
greptimedb           |   28: <unknown>
greptimedb           |   29: <unknown>
greptimedb           |   30: <unknown>
greptimedb           |   31: <unknown>
greptimedb           |   32: <unknown>
greptimedb           |   33: <unknown>
greptimedb           |   34: <unknown>
greptimedb           |   35: <unknown>
greptimedb           |   36: <unknown>
greptimedb           |   37: <unknown>
greptimedb           |   38: <unknown>
greptimedb           |   39: <unknown>
greptimedb           |   40: <unknown>
greptimedb           |   41: <unknown>
greptimedb           |   42: <unknown>
greptimedb           |   43: <unknown>
greptimedb           |   44: <unknown>
greptimedb           |   45: <unknown>
greptimedb           |   46: <unknown>
greptimedb           |   47: <unknown>
greptimedb           |   48: <unknown>
greptimedb           |   49: <unknown>
greptimedb           |   50: <unknown>
greptimedb           |   51: <unknown>
greptimedb           |   52: <unknown>
greptimedb           |   53: <unknown>
greptimedb           |   54: <unknown>
greptimedb           |   55: <unknown>
greptimedb           |   56: <unknown>
greptimedb           |   57: <unknown>
greptimedb           |   58: <unknown>
greptimedb           |   59: <unknown>
greptimedb           |   60: <unknown>
greptimedb           |   61: <unknown>
greptimedb           |   62: <unknown>
greptimedb           |   63: <unknown>
greptimedb           |   64: <unknown>
greptimedb           |   65: <unknown>
greptimedb           |   66: __clone
greptimedb           |  panic.file="/greptimedb/src/datatypes/src/vectors/helper.rs" panic.line=323 panic.column=17
```

### What operating system did you use?

Mac OS X

### How can we reproduce the bug?

please see what happened

**Comment by waynexia** [comment]
This panic is fixed in https://github.com/GreptimeTeam/greptimedb/pull/2351. The query `node_cpu_seconds_total{mode="idle"}[5m]` is expected to return an error as the result is a [range selector](https://prometheus.io/docs/prometheus/latest/querying/basics/#range-vector-selectors), which can not be used as the final type but only as an intermediate result. Try something like `sum(node_cpu_seconds_total{mode="idle"}[5m])`.

But the error message should be improved. This is `InvalidArguments` rather than `Internal`

**Comment by waynexia** [comment]
The error message is improved in https://github.com/GreptimeTeam/greptimedb/pull/2883:
```
2023-12-13T03:59:18.209588Z ERROR frontend::instance: Failed to execute query: tql eval (1702438983, 1702438983, '30s') sum(node_cpu_seconds_total{mode="idle"}[5m]) err=0: Table operation error, at src/frontend/src/instance.rs:247:14
1: Failed to parse query, at /home/wayne/repo/greptimedb/src/operator/src/statement/tql.rs:38:60
2: Failure during query parsing, query: sum(node_cpu_seconds_total{mode="idle"}[5m]), at src/query/src/parser.rs:129:14
3: expected type vector in aggregation expression, got matrix
```
