### ISSUE TITLE
panic at  src/mito2/src/memtable/time_series.rs:188:52

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2480]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Datanode

### What happened?

Running the java example more than once

 https://docs.greptime.com/user-guide/write-data/sdk-libraries/java 

After the first execution, the second execution panic at `src/mito2/src/memtable/time_series.rs:188:52`

```
2023-09-24T15:32:18.541899Z ERROR common_telemetry::panic_hook: panicked at src/mito2/src/memtable/time_series.rs:188:52:
called `Result::unwrap()` on an `Err` value: CastType { msg: "Failed to cast value ref Int64(1695569538016) to Timestamp", location: Location { file: "src/datatypes/src/value.rs", line: 959, column: 9 } } backtrace=   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
 panic.file="src/mito2/src/memtable/time_series.rs" panic.line=188 panic.column=52
```

Then the worker 0 exited:

```
2023-09-24T15:33:07.130925Z  WARN mito2::worker: Worker 0 is already exited but the running flag is still true
2023-09-24T15:33:07.131683Z ERROR servers::grpc::greptime_handler: Failed to handle request trace_id=0 err.msg=Failed to insert data, source: Failed to handle request for region 4402341478400(1025, 0), source: Worker 0 is stopped, location: src/mito2/src/worker.rs:297:55, location: src/datanode/src/region_server.rs:263:14 err.code=Internal err.source=Failed to insert data, source: Failed to handle request for region 4402341478400(1025, 0), source: Worker 0 is stopped, location: src/mito2/src/worker.rs:297:55, location: src/datanode/src/region_server.rs:263:14 err.source.sources=[Failed to insert data, source: Failed to handle request for region 4402341478400(1025, 0), source: Worker 0 is stopped, location: src/mito2/src/worker.rs:297:55, location: src/datanode/src/region_server.rs:263:14, Failed to handle request for region 4402341478400(1025, 0), source: Worker 0 is stopped, location: src/mito2/src/worker.rs:297:55, location: src/datanode/src/region_server.rs:263:14, Failed to handle request for region 4402341478400(1025, 0), source: Worker 0 is stopped, location: src/mito2/src/worker.rs:297:55, location: src/datanode/src/region_server.rs:263:14, Failed to handle request for region 4402341478400(1025, 0), source: Worker 0 is stopped, location: src/mito2/src/worker.rs:297:55, location: src/datanode/src/region_server.rs:263:14, Failed to handle request for region 4402341478400(1025, 0), source: Worker 0 is stopped, location: src/mito2/src/worker.rs:297:55, location: src/datanode/src/region_server.rs:263:14, Worker 0 is stopped, location: src/mito2/src/worker.rs:297:55]
```

### What operating system did you use?

All system

### How can we reproduce the bug?

Run the java write example more than once

https://docs.greptime.com/user-guide/write-data/sdk-libraries/java

**Comment by killme2008** [comment]
Looks like it's the document issue, it's outdated for v0.4

**Comment by evenyag** [comment]
https://github.com/GreptimeTeam/greptimedb/pull/2460 should fix this.
