### ISSUE TITLE
Meta heartbeat handler loop panic

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#2885]
### What type of bug is this?

Crash

### What subsystems are affected?

Meta

### Minimal reproduce step

Accidentally

### What did you expect to see?

It should quit the heartbeat handler loop normally if the receiver is dropped.

### What did you see instead?

Panic

### What operating system did you use?

Doesn't matter

### Relevant log output and stack trace

```bash
2023-12-06 22:22:34.141	
2023-12-06T13:22:34.141244Z  INFO meta_srv::handler: Pusher register: 0-1
2023-12-06 22:22:34.141	
2023-12-06T13:22:34.141316Z  WARN meta_srv::handler::collect_stats_handler: Incomplete heartbeat data: HeartbeatRequest { header: Some(RequestHeader { protocol_version: 1, cluster_id: 0, member_id: 1, role: Datanode, tracing_context: {} }), peer: None, report_interval: None, region_stats: [], mailbox_message: None, duration_since_epoch: 0, node_epoch: 0 }, err: 0: Invalid heartbeat request: missing header or peer, at greptimedb/src/meta-srv/src/handler/node_stat.rs:130:14
2023-12-06 22:22:34.357	
2023-12-06T13:22:34.357808Z  WARN meta_srv::handler::collect_stats_handler: Incomplete heartbeat data: HeartbeatRequest { header: Some(RequestHeader { protocol_version: 1, cluster_id: 0, member_id: 0, role: Datanode, tracing_context: {} }), peer: None, report_interval: None, region_stats: [], mailbox_message: None, duration_since_epoch: 0, node_epoch: 0 }, err: 0: Invalid heartbeat request: missing header or peer, at greptimedb/src/meta-srv/src/handler/node_stat.rs:130:14
2023-12-06 22:22:34.358	
2023-12-06T13:22:34.358099Z ERROR common_telemetry::panic_hook: panicked at greptimedb/src/meta-srv/src/service/heartbeat.rs:81:44:
2023-12-06 22:22:34.358	
working rx: SendError { .. } backtrace=   0: common_telemetry::panic_hook::set_panic_hook::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/work/greptimedb-cloud/greptimedb-cloud/greptimedb/src/common/telemetry/src/panic_hook.rs:37:25
2023-12-06 22:22:34.358	
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/boxed.rs:2021:9
2023-12-06 22:22:34.358	
      std::panicking::rust_panic_with_hook
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:735:13
2023-12-06 22:22:34.358	
   2: std::panicking::begin_panic_handler::{{closure}}
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:609:13
2023-12-06 22:22:34.358	
   3: std::sys_common::backtrace::__rust_end_short_backtrace
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/sys_common/backtrace.rs:170:18
2023-12-06 22:22:34.358	
   4: rust_begin_unwind
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:597:5
2023-12-06 22:22:34.358	
   5: core::panicking::panic_fmt
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panicking.rs:72:14
2023-12-06 22:22:34.358	
   6: core::result::unwrap_failed
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/result.rs:1653:5
2023-12-06 22:22:34.358	
   7: core::result::Result<T,E>::expect
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/result.rs:1034:23
2023-12-06 22:22:34.358	
      meta_srv::service::heartbeat::<impl greptime_proto::v1::meta::heartbeat_server::Heartbeat for meta_srv::metasrv::MetaSrv>::heartbeat::{{closure}}::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/work/greptimedb-cloud/greptimedb-cloud/greptimedb/src/meta-srv/src/service/heartbeat.rs:81:25
2023-12-06 22:22:34.358	
   8: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/core.rs:328:17
2023-12-06 22:22:34.358	
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/loom/std/unsafe_cell.rs:16:9
2023-12-06 22:22:34.358	
      tokio::runtime::task::core::Core<T,S>::poll
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/core.rs:317:13
2023-12-06 22:22:34.358	
   9: tokio::runtime::task::harness::poll_future::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/harness.rs:485:19
2023-12-06 22:22:34.358	
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panic/unwind_safe.rs:271:9
2023-12-06 22:22:34.358	
      std::panicking::try::do_call
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:504:40
2023-12-06 22:22:34.358	
      std::panicking::try
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:468:19
2023-12-06 22:22:34.358	
      std::panic::catch_unwind
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panic.rs:142:14
2023-12-06 22:22:34.358	
      tokio::runtime::task::harness::poll_future
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/harness.rs:473:18
2023-12-06 22:22:34.358	
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/harness.rs:208:27
2023-12-06 22:22:34.358	
      tokio::runtime::task::harness::Harness<T,S>::poll
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/harness.rs:153:15
2023-12-06 22:22:34.358	
  10: tokio::runtime::task::raw::RawTask::poll
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/raw.rs:201:18
2023-12-06 22:22:34.358	
      tokio::runtime::task::LocalNotified<S>::run
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/mod.rs:408:9
2023-12-06 22:22:34.358	
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:577:18
2023-12-06 22:22:34.358	
      tokio::runtime::coop::with_budget
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/coop.rs:107:5
2023-12-06 22:22:34.358	
      tokio::runtime::coop::budget
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/coop.rs:73:5
2023-12-06 22:22:34.358	
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:576:9
2023-12-06 22:22:34.358	
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
2023-12-06 22:22:34.358	
  12: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
2023-12-06 22:22:34.358	
      tokio::runtime::context::scoped::Scoped<T>::set
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/context/scoped.rs:40:9
2023-12-06 22:22:34.358	
      tokio::runtime::context::set_scheduler::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/context.rs:176:26
2023-12-06 22:22:34.358	
      std::thread::local::LocalKey<T>::try_with
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/local.rs:270:16
2023-12-06 22:22:34.358	
      std::thread::local::LocalKey<T>::with
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/local.rs:246:9
2023-12-06 22:22:34.358	
      tokio::runtime::context::set_scheduler
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/context.rs:176:17
2023-12-06 22:22:34.358	
  13: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
2023-12-06 22:22:34.358	
      tokio::runtime::context::runtime::enter_runtime
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/context/runtime.rs:65:16
2023-12-06 22:22:34.358	
  14: tokio::runtime::scheduler::multi_thread::worker::run
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
2023-12-06 22:22:34.358	
  15: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
2023-12-06 22:22:34.358	
      <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/blocking/task.rs:42:21
2023-12-06 22:22:34.358	
  16: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/core.rs:328:17
2023-12-06 22:22:34.358	
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/loom/std/unsafe_cell.rs:16:9
2023-12-06 22:22:34.358	
      tokio::runtime::task::core::Core<T,S>::poll
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/core.rs:317:13
2023-12-06 22:22:34.358	
  17: tokio::runtime::task::harness::poll_future::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/harness.rs:485:19
2023-12-06 22:22:34.358	
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panic/unwind_safe.rs:271:9
2023-12-06 22:22:34.358	
      std::panicking::try::do_call
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:504:40
2023-12-06 22:22:34.358	
      std::panicking::try
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:468:19
2023-12-06 22:22:34.358	
      std::panic::catch_unwind
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panic.rs:142:14
2023-12-06 22:22:34.358	
      tokio::runtime::task::harness::poll_future
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/harness.rs:473:18
2023-12-06 22:22:34.358	
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/harness.rs:208:27
2023-12-06 22:22:34.358	
      tokio::runtime::task::harness::Harness<T,S>::poll
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/harness.rs:153:15
2023-12-06 22:22:34.358	
  18: tokio::runtime::task::raw::RawTask::poll
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/raw.rs:201:18



2023-12-06 22:22:34.358	
      tokio::runtime::task::UnownedTask<S>::run
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/task/mod.rs:445:9
2023-12-06 22:22:34.358	
      tokio::runtime::blocking::pool::Task::run
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/blocking/pool.rs:159:9
2023-12-06 22:22:34.358	
      tokio::runtime::blocking::pool::Inner::run
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/blocking/pool.rs:513:17
2023-12-06 22:22:34.358	
  19: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
2023-12-06 22:22:34.358	
             at home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/blocking/pool.rs:471:13
2023-12-06 22:22:34.358	
      std::sys_common::backtrace::__rust_begin_short_backtrace
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/sys_common/backtrace.rs:154:18
2023-12-06 22:22:34.358	
  20: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/mod.rs:529:17
2023-12-06 22:22:34.358	
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panic/unwind_safe.rs:271:9
2023-12-06 22:22:34.358	
      std::panicking::try::do_call
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:504:40
2023-12-06 22:22:34.358	
      std::panicking::try
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:468:19
2023-12-06 22:22:34.358	
      std::panic::catch_unwind
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panic.rs:142:14
2023-12-06 22:22:34.358	
      std::thread::Builder::spawn_unchecked_::{{closure}}
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/mod.rs:528:30
2023-12-06 22:22:34.358	
      core::ops::function::FnOnce::call_once{{vtable.shim}}
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/ops/function.rs:250:5
2023-12-06 22:22:34.358	
  21: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/boxed.rs:2007:9
2023-12-06 22:22:34.358	
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/boxed.rs:2007:9
2023-12-06 22:22:34.358	
      std::sys::unix::thread::Thread::new::thread_start
2023-12-06 22:22:34.358	
             at rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/sys/unix/thread.rs:108:17
2023-12-06 22:22:34.358	
  22: <unknown>
2023-12-06 22:22:34.358	
  23: __clone
2023-12-06 22:22:34.358	
 panic.file="greptimedb/src/meta-srv/src/service/heartbeat.rs" panic.line=81 panic.column=44
2023-12-06 22:22:34.358	
thread 'bg-worker' panicked at greptimedb/src/meta-srv/src/service/heartbeat.rs:81:44:
2023-12-06 22:22:34.358	
working rx: SendError { .. }
```

**Comment by tisonkun** [comment]
@WenyXu If this panic happens during shutting down, perhaps we just need to gracefully handle the error and exit the thread without panic.
