### ISSUE TITLE
Test failed when upgrading to `chrono` 0.4.32

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/greptimedb#3228]
### What type of bug is this?

Other

### What subsystems are affected?

Other

### Minimal reproduce step

cargo update then run test "`test_from_naive_date_time`"

### What did you expect to see?

the test passed

### What did you see instead?

```text
Cannot convert Timestamp { value: -8334632851200, unit: Second } to Chrono NaiveDateTime
thread 'timestamp::tests::test_from_naive_date_time' panicked at src/common/time/src/timestamp.rs:1240:17:
Cannot convert Timestamp { value: -8334632851200, unit: Second } to Chrono NaiveDateTime
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panicking.rs:72:14
   2: common_time::timestamp::tests::check_conversion
             at ./src/timestamp.rs:1240:17
   3: common_time::timestamp::tests::test_from_naive_date_time
             at ./src/timestamp.rs:1258:9
   4: common_time::timestamp::tests::test_from_naive_date_time::{{closure}}
             at ./src/timestamp.rs:1255:35
   5: core::ops::function::FnOnce::call_once
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/ops/function.rs:250:5
```

### What operating system did you use?

macos

### What version of GreptimeDB did you use?

main

**Comment by sunng87** [comment]
It's chrono changing it supported max/min year since 0.4.32: https://github.com/chronotope/chrono/issues/1382
