### ISSUE TITLE
Panic when disk is full

### ISSUE THREAD

**Issue by waynexia** [GreptimeTeam/greptimedb#3292]
### What type of bug is this?

Crash

### What subsystems are affected?

Storage Engine

### Minimal reproduce step

1. Start server
2. Write data
3. Wait for disk full

### What did you expect to see?

Throw an error instead of panic

### What did you see instead?

```
2024-02-06T17:21:24.435127Z  INFO mito2::flush: Successfully flush memtables, region: 4398046511104(1024, 0), reason: EngineFull, files: [FileId(7e85190d-63ce-4578-89ae-1815068cdb7b)], cost: 33.598627949s
2024-02-06T17:21:24.435200Z ERROR mito2::sst::file_purger: Failed to schedule the file purge request err=0: Invalid scheduler state, at src/mito2/src/schedule/scheduler.rs:116:9
2024-02-06T17:22:34.232212Z ERROR log: service=fs operation=Writer::close path=__intm/4398046511104/03bb1824-f6f7-4751-9ca6-511b363cbe30/e7dce422-13d8-4d97-a21c-3a26536998d0/2147483651/000074644960.im written=1087307B -> data close failed: Unexpected (temporary) at Writer::close, context: { service: fs, path: __intm/4398046511104/03bb1824-f6f7-4751-9ca6-511b363cbe30/e7dce422-13d8-4d97-a21c-3a26536998d0/2147483651/000074644960.im } => no storage space, source: No space left on device (os error 28)    
2024-02-06T17:22:34.233209Z ERROR log: service=fs operation=Writer::close path=__intm/4398046511104/89208648-a0e4-47c8-b470-ea75862f0a05/2473c044-98b1-410e-82ca-285dbdd2851f/2147483651/000157108138.im written=1094590B -> data close failed: Unexpected (temporary) at Writer::close, context: { service: fs, path: __intm/4398046511104/89208648-a0e4-47c8-b470-ea75862f0a05/2473c044-98b1-410e-82ca-285dbdd2851f/2147483651/000157108138.im } => no storage space, source: No space left on device (os error 28)    
```

<details><summary>Backtrace</summary>
<p>

```
2024-02-06T17:22:34.450952Z ERROR common_telemetry::panic_hook: panicked at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/services/fs/writer.rs:75:39:
FsWriter must be initialized backtrace=   0: common_telemetry::panic_hook::set_panic_hook::{{closure}}
             at src/common/telemetry/src/panic_hook.rs:37:25
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panicking.rs:72:14
   6: core::panicking::panic_display
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panicking.rs:196:5
      core::panicking::panic_str
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panicking.rs:171:5
      core::option::expect_failed
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/option.rs:1980:5
   7: core::option::Option<T>::expect
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/option.rs:894:21
      <opendal::services::fs::writer::FsWriter<tokio::fs::file::File> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/services/fs/writer.rs:75:39
   8: <opendal::layers::error_context::ErrorContextWrapper<T> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/layers/error_context.rs:420:9
   9: <opendal::layers::complete::CompleteWriter<W> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/layers/complete.rs:728:16
  10: <opendal::raw::oio::write::exact_buf_write::ExactBufWriter<W> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/raw/oio/write/exact_buf_write.rs:74:9
  11: <opendal::raw::enum_utils::TwoWays<ONE,TWO> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/raw/enum_utils.rs:117:29
  12: <alloc::boxed::Box<T> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/raw/oio/write/api.rs:125:9
      <opendal::layers::logging::LoggingWriter<W> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/layers/logging.rs:1336:22
  13: <alloc::boxed::Box<T> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/raw/oio/write/api.rs:125:9
      <opendal::layers::tracing::TracingWrapper<R> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/layers/tracing.rs:344:9
  14: <alloc::boxed::Box<T> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/raw/oio/write/api.rs:125:9
      <object_store::layers::prometheus::PrometheusMetricWrapper<R> as opendal::raw::oio::write::api::Write>::poll_close
             at src/object-store/src/layers/prometheus.rs:533:9
  15: <alloc::boxed::Box<T> as opendal::raw::oio::write::api::Write>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/raw/oio/write/api.rs:125:9
      <opendal::types::writer::Writer as futures_io::if_std::AsyncWrite>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/types/writer.rs:230:14
  16: <alloc::boxed::Box<T> as futures_io::if_std::AsyncWrite>::poll_close
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-io-0.3.30/src/lib.rs:397:17
      <futures_util::io::close::Close<W> as core::future::future::Future>::poll
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/io/close.rs:26:9
      index::inverted_index::create::sort::intermediate_rw::IntermediateWriter<W>::write_all::{{closure}}
             at src/index/src/inverted_index/create/sort/intermediate_rw.rs:55:33
      index::inverted_index::create::sort::external_sort::ExternalSorter::may_dump_buffer::{{closure}}
             at src/index/src/inverted_index/create/sort/external_sort.rs:201:59
      <index::inverted_index::create::sort::external_sort::ExternalSorter as index::inverted_index::create::sort::Sorter>::push_n::{{closure}}
             at src/index/src/inverted_index/create/sort/external_sort.rs:80:47
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/future/future.rs:124:9
      <index::inverted_index::create::sort_create::SortIndexCreator as index::inverted_index::create::InvertedIndexCreator>::push_with_name_n::{{closure}}
             at src/index/src/inverted_index/create/sort_create.rs:59:53
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/future/future.rs:124:9
      mito2::sst::index::creator::SstIndexCreator::do_update::{{closure}}
             at src/mito2/src/sst/index/creator.rs:201:18
      mito2::sst::index::creator::SstIndexCreator::update::{{closure}}
             at src/mito2/src/sst/index/creator.rs:131:56
      mito2::sst::index::Indexer::update::{{closure}}
             at src/mito2/src/sst/index.rs:54:53
      mito2::sst::parquet::writer::ParquetWriter::write_all::{{closure}}
             at src/mito2/src/sst/parquet/writer.rs:109:41
  19: mito2::access_layer::AccessLayer::write_sst::{{closure}}
             at src/mito2/src/access_layer.rs:154:58
      mito2::compaction::twcs::TwcsCompactionTask::merge_ssts::{{closure}}::{{closure}}
             at src/mito2/src/compaction/twcs.rs:347:22
  20: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/core.rs:328:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/loom/std/unsafe_cell.rs:16:9
      tokio::runtime::task::core::Core<T,S>::poll
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/core.rs:317:13
  21: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:485:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panic.rs:142:14
      tokio::runtime::task::harness::poll_future
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:473:18
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:208:27
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:153:15
      tokio::runtime::task::raw::poll
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/raw.rs:271:5
  22: tokio::runtime::task::raw::RawTask::poll
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/raw.rs:201:18
      tokio::runtime::task::LocalNotified<S>::run
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/mod.rs:416:9
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:576:18
      tokio::runtime::coop::with_budget
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:73:5
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:575:9
  23: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:526:24
  24: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:491:21
      tokio::runtime::context::scoped::Scoped<T>::set
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/scoped.rs:40:9
      tokio::runtime::context::set_scheduler::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context.rs:176:26
      std::thread::local::LocalKey<T>::try_with
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/thread/local.rs:270:16
      std::thread::local::LocalKey<T>::with
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/thread/local.rs:246:9
      tokio::runtime::context::set_scheduler
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context.rs:176:17
  25: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:486:9
      tokio::runtime::context::runtime::enter_runtime
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/runtime.rs:65:16
  26: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:478:5
  27: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/worker.rs:447:45
      <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/task.rs:42:21
  28: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/core.rs:328:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/loom/std/unsafe_cell.rs:16:9
      tokio::runtime::task::core::Core<T,S>::poll
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/core.rs:317:13
  29: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:485:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panic.rs:142:14
      tokio::runtime::task::harness::poll_future
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:473:18
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:208:27
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/harness.rs:153:15
  30: tokio::runtime::task::raw::RawTask::poll
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/raw.rs:201:18
      tokio::runtime::task::UnownedTask<S>::run
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/task/mod.rs:453:9
      tokio::runtime::blocking::pool::Task::run
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/pool.rs:159:9
      tokio::runtime::blocking::pool::Inner::run
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/pool.rs:513:17
  31: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/pool.rs:471:13
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/sys_common/backtrace.rs:155:18
  32: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/core/src/ops/function.rs:250:5
  33: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/alloc/src/boxed.rs:2015:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/alloc/src/boxed.rs:2015:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library/std/src/sys/unix/thread.rs:108:17
  34: <unknown>
  35: <unknown>
 panic.file="/home/wayne/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.44.2/src/services/fs/writer.rs" panic.line=75 panic.column=39
```

</p>
</details> 

### What operating system did you use?

6.6.5-arch1-1

### What version of GreptimeDB did you use?

e4cd294

**Comment by waynexia** [comment]
This might relate to https://github.com/apache/opendal/issues/4058
