### ISSUE TITLE
list_files_and_parse_table_name failed on windows

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#3301]
### What type of bug is this?

Other

### What subsystems are affected?

Standalone mode, Frontend

### Minimal reproduce step

Run `cargo nextest run`

### What did you expect to see?

All tests pass

### What did you see instead?

```
thread 'statement::copy_database::tests::test_list_files_and_parse_table_name' panicked at src\operator\src\statement\copy_database.rs:238:14:
called `Result::unwrap()` on an `Err` value: 0: Failed to build data source backend, at src\operator\src\statement\copy_database.rs:190:55
1: Unsupported backend protocol: c, url: C:\Users\RUNNER~1\AppData\Local\Temp\test_list_files_to_copyFJZhrl/, at src\common\datasource\src\object_store.rs:73:10
stack backtrace:
```

### What operating system did you use?

Windows

### What version of GreptimeDB did you use?

latest

### Relevant log output and stack trace

```bash
thread 'statement::copy_database::tests::test_list_files_and_parse_table_name' panicked at src\operator\src\statement\copy_database.rs:238:14:
called `Result::unwrap()` on an `Err` value: 0: Failed to build data source backend, at src\operator\src\statement\copy_database.rs:190:55
1: Unsupported backend protocol: c, url: C:\Users\RUNNER~1\AppData\Local\Temp\test_list_files_to_copyFJZhrl/, at src\common\datasource\src\object_store.rs:73:10
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library\core\src\panicking.rs:72
   2: core::result::unwrap_failed
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library\core\src\result.rs:1649
   3: enum2$<core::result::Result<alloc::vec::Vec<opendal::types::entry::Entry,alloc::alloc::Global>,enum2$<operator::error::Error> > >::unwrap<alloc::vec::Vec<opendal::types::entry::Entry,alloc::alloc::Global>,enum2$<operator::error::Error> >
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c\library\core\src\result.rs:1073
   4: operator::statement::copy_database::tests::test_list_files_and_parse_table_name::async_block$0
             at .\src\statement\copy_database.rs:236
   5: core::future::future::impl$1::poll<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > >
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c\library\core\src\future\future.rs:124
   6: core::future::future::impl$1::poll<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > > >
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c\library\core\src\future\future.rs:124
   7: tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0::closure$0::closure$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > > > >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\current_thread\mod.rs:665
   8: tokio::runtime::coop::with_budget
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\coop.rs:107
   9: tokio::runtime::coop::budget
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\coop.rs:73
  10: tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0::closure$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > > > >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\current_thread\mod.rs:665
  11: tokio::runtime::scheduler::current_thread::Context::enter<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0::closure_env$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::f
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\current_thread\mod.rs:410
  12: tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > > > >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\current_thread\mod.rs:664
  13: tokio::runtime::scheduler::current_thread::impl$8::enter::closure$0<tokio::runtime::scheduler::current_thread::impl$8::block_on::closure_env$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\current_thread\mod.rs:743
  14: tokio::runtime::context::scoped::Scoped<enum2$<tokio::runtime::scheduler::Context> >::set<enum2$<tokio::runtime::scheduler::Context>,tokio::runtime::scheduler::current_thread::impl$8::enter::closure_env$0<tokio::runtime::scheduler::current_thread::impl$8:
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\context\scoped.rs:40
  15: tokio::runtime::context::set_scheduler::closure$0<tuple$<alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core,alloc::alloc::Global>,enum2$<core::option::Option<tuple$<> > > >,tokio::runtime::scheduler::current_thread::impl$8::enter::closure_e
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\context.rs:176
  16: std::thread::local::LocalKey<tokio::runtime::context::Context>::try_with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core,alloc::alloc::Global>,
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c\library\std\src\thread\local.rs:270
  17: std::thread::local::LocalKey<tokio::runtime::context::Context>::with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core,alloc::alloc::Global>,enum
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c\library\std\src\thread\local.rs:246
  18: tokio::runtime::context::set_scheduler<tuple$<alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core,alloc::alloc::Global>,enum2$<core::option::Option<tuple$<> > > >,tokio::runtime::scheduler::current_thread::impl$8::enter::closure_env$0<tokio:
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\context.rs:176
  19: tokio::runtime::scheduler::current_thread::CoreGuard::enter<tokio::runtime::scheduler::current_thread::impl$8::block_on::closure_env$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > > > >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\current_thread\mod.rs:743
  20: tokio::runtime::scheduler::current_thread::CoreGuard::block_on<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > > > >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\current_thread\mod.rs:652
  21: tokio::runtime::scheduler::current_thread::impl$0::block_on::closure$0<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\current_thread\mod.rs:175
  22: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::current_thread::impl$0::block_on::closure_env$0<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > >,tuple$<> >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\context\runtime.rs:65
  23: tokio::runtime::scheduler::current_thread::CurrentThread::block_on<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\current_thread\mod.rs:167
  24: tokio::runtime::runtime::Runtime::block_on<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,tuple$<> > > > > > >
             at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\runtime.rs:348
  25: operator::statement::copy_database::tests::test_list_files_and_parse_table_name
             at .\src\statement\copy_database.rs:243
  26: operator::statement::copy_database::tests::test_list_files_and_parse_table_name::closure$0
             at .\src\statement\copy_database.rs:214
  27: core::ops::function::FnOnce::call_once<operator::statement::copy_database::tests::test_list_files_and_parse_table_name::closure_env$0,tuple$<> >
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c\library\core\src\ops\function.rs:250
  28: core::ops::function::FnOnce::call_once
             at /rustc/3f28fe133475ec5faf3413b556bf3cfb0d51336c/library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by WenyXu** [comment]
Related to #3280

**Comment by evenyag** [comment]
> Related to #3280

The test had failed before we merged it.

https://github.com/GreptimeTeam/greptimedb/actions/runs/7618496085/job/20749790638

It should be related to https://github.com/GreptimeTeam/greptimedb/pull/3164

**Comment by WenyXu** [comment]
> > Related to #3280
> 
> The test had failed before we merged it.
> 
> https://github.com/GreptimeTeam/greptimedb/actions/runs/7618496085/job/20749790638
> 
> It should be related to #3164

🥹 BTW, I will try to add a free CI test on Windows for each PR request(I'm not sure whether the 4 core is enough for tests)

**Comment by evenyag** [comment]
We can use [path-slash](https://github.com/rhysd/path-slash) to change the path as a workaround.

A similar crate is [typed-path](https://github.com/chipsenkbeil/typed-path).
