### ISSUE TITLE
Compatible with InfluxDB authentication

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/greptimedb#3436]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Write Protocols

### Minimal reproduce step

Try the demo from influxdb-java:

```java
        final String serverURL = "https://xxx.greptime.cloud/v1/influxdb/";
        final String username = "yyy";
        final String password = "zzz";
        try (final InfluxDB influxDB = InfluxDBFactory.connect(serverURL, username, password)) {
            influxDB.setDatabase("ddd-public");
            influxDB.write(Point.measurement("h2o_feet")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .tag("location", "santa_monica")
                    .addField("level description", "below 3 feet")
                    .addField("water_level", 2.064d)
                    .build());

            influxDB.write(Point.measurement("h2o_feet")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .tag("location", "coyote_creek")
                    .addField("level description", "between 6 and 9 feet")
                    .addField("water_level", 8.12d)
                    .build());

            // Wait a few seconds in order to let the InfluxDB client
// write your points asynchronously (note: you can adjust the
// internal time interval if you need via 'enableBatch' call).
            Thread.sleep(5_000L);

// Query your data using InfluxQL.
// https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#the-basic-select-statement
            QueryResult queryResult = influxDB.query(new Query("SELECT * FROM h2o_feet"));
            System.out.println(queryResult);
```

### What did you expect to see?

Properly write and query.

### What did you see instead?

```
Exception in thread "main" org.influxdb.InfluxDBException: Unsupported http auth scheme, name: Basic
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:161)
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:846)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:470)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:441)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:419)
	at org.example.Main.main(Main.java:17)
```

### What operating system did you use?

Mac OS X 13.4 ARM

### What version of GreptimeDB did you use?

GreptimeCloud

### Relevant log output and stack trace

It seems we check only `Authorization: token ...` when the header is set. However, InfluxDB official clients use `Authroization: Basic ..` for v1 request:

* https://github.com/influxdata/influxdb-java 

https://github.com/influxdata/influxdb-java/blob/0c690c8d8a6627f525e05d68e0571e089c61845e/src/main/java/org/influxdb/impl/InfluxDBImpl.java#L153-L155

* https://github.com/influxdata/influxdb-python

https://github.com/influxdata/influxdb-python/blob/915b79a35aa11501866d3134f244500644a20e1e/influxdb/client.py#L339-L354

```rust
fn get_influxdb_credentials<B>(request: &Request<B>) -> Result<Option<(Username, Password)>> {
    // compat with influxdb v2 and v1
    if let Some(header) = request.headers().get(http::header::AUTHORIZATION) {
        // try v2 first
        let (auth_scheme, credential) = header
            .to_str()
            .context(InvisibleASCIISnafu)?
            .split_once(' ')
            .context(InvalidAuthorizationHeaderSnafu)?;
        ensure!(
            auth_scheme.to_lowercase() == "token",
            UnsupportedAuthSchemeSnafu { name: auth_scheme }
        );

        let (username, password) = credential
            .split_once(':')
            .context(InvalidAuthorizationHeaderSnafu)?;

        Ok(Some((username.to_string(), password.to_string().into())))
    } else {
        // try v1
```

**Comment by tisonkun** [comment]
A quick solution is changing `auth_scheme.to_lowercase() == "token",` with `matches!(auth_scheme.to_lowercase().as_str(), "token" | "basic"),`, but we have to ensure that such changes won't introduce new issues.
