### ISSUE TITLE
Failed to run fuzz tests with cluster run on MinIO + Disk Cache

### ISSUE THREAD

**Issue by WenyXu** [GreptimeTeam/greptimedb#4115]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Distributed Cluster, Query Engine

### Minimal reproduce step

1. Boot GreptimeDB cluster (Minio + Disk Cache)
2. Run fuzz tests

### What did you expect to see?

Check https://github.com/GreptimeTeam/greptimedb/actions/runs/9404816932?pr=4105

### What did you see instead?

2024-06-06T17:06:31.515512Z  INFO fuzz_alter_table: Alter table: ALTER TABLE `at` ADD COLUMN sunt INT DEFAULT -1898871454;, result: MySqlQueryResult { rows_affected: 0, last_insert_id: 0 }
2024-06-06T17:06:34.537403Z  WARN log: SELECT table_schema, table_name, column_name, …; rows affected: 0, rows returned: 0, elapsed: 3.015s
thread '<unnamed>' panicked at tests-fuzz/targets/fuzz_alter_table.rs:197:35:
fuzz test must be succeed: 0: Failed to execute query: SELECT table_schema, table_name, column_name, greptime_data_type as data_type, semantic_type, column_default, is_nullable FROM information_schema.columns WHERE table_schema = ? AND table_name = ?, at /home/runner/work/greptimedb/greptimedb/tests-fuzz/src/validator/column.rs:220:10

### What operating system did you use?

doesn't matter

### What version of GreptimeDB did you use?

main

**Comment by killme2008** [comment]
Another failure https://github.com/GreptimeTeam/greptimedb/actions/runs/9591355996/job/26448404060

```
2024-06-20T04:12:27.9857530Z thread ‘<unnamed>’ panicked at tests-fuzz/targets/fuzz_alter_logical_table.rs:238:35:
2024-06-20T04:12:27.9859587Z fuzz test must be succeed: 0: Failed to execute query: ALTER TABLE `REicieNDIS` ADD COLUMN non STRING PRIMARY KEY;, at tests-fuzz/targets/fuzz_alter_logical_table.rs:173:14
2024-06-20T04:12:27.9861522Z 1: Database(MySqlDatabaseError { code: Some(“HY000”), number: 1815, message: “Internal error: 1003" })
2024-06-20T04:12:27.9862782Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
