### ISSUE TITLE
Fuzz test failure Distributed, Minio, fuzz_insert_logical_table

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#4120]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Distributed Cluster

### Minimal reproduce step

The link

https://github.com/GreptimeTeam/greptimedb/actions/runs/9424315092/job/25964368555

and the log:

```
2024-06-07T23:44:34.056444Z  WARN log: CREATE TABLE IF NOT …; rows affected: 0, rows returned: 0, elapsed: 12.776s

CREATE TABLE IF NOT EXISTS `pOssiMus`(
  ts TIMESTAMP(3) TIME INDEX,
  val DOUBLE,
  `ADIPIsCI` STRING,
  `REPeLLENDUS` STRING,
  `mODI` STRING,
  PRIMARY KEY(`REPeLLENDUS`, `ADIPIsCI`, `mODI`)
) ENGINE = metric with ("on_physical_table" = "doLORuM");
  
thread '<unnamed>' panicked at tests-fuzz/targets/fuzz_insert_logical_table.rs:307:35:
fuzz test must be succeed: 0: Failed to execute query: CREATE TABLE IF NOT EXISTS `pOssiMus`(
ts TIMESTAMP(3) TIME INDEX,
val DOUBLE,
`ADIPIsCI` STRING,
`REPeLLENDUS` STRING,
`mODI` STRING,
PRIMARY KEY(`REPeLLENDUS`, `ADIPIsCI`, `mODI`)
)
ENGINE=metric with ("on_physical_table" = "doLORuM");, at tests-fuzz/targets/fuzz_insert_logical_table.rs:256:14
1: Database(MySqlDatabaseError { code: Some("HY000"), number: 1815, message: "Internal error: 1003" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==18642== ERROR: libFuzzer: deadly signal
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xa,
\012
artifact_prefix='tests-fuzz/artifacts/fuzz_insert_logical_table/'; Test unit written to tests-fuzz/artifacts/fuzz_insert_logical_table/crash-adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
Base64: Cg==

────────────────────────────────────────────────────────────────────────────────

Failing input:

	tests-fuzz/artifacts/fuzz_insert_logical_table/crash-adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
```

### What did you expect to see?

Success

### What did you see instead?

fail

### What operating system did you use?

Not relevant

### What version of GreptimeDB did you use?

main branch

**Comment by WenyXu** [comment]
A known issue, it should be related to #4119

**Comment by killme2008** [comment]
> A known issue, it should be related to #4119

Let's see if it exists after #4119 is merged.
