### ISSUE TITLE
test failures on tests-integration/tests/sql.rs after cargo postgres dependency upgrade 

### ISSUE THREAD

**Issue by lyang24** [GreptimeTeam/greptimedb#4503]
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Query Engine

### Minimal reproduce step
I introduced tokio-postgres 0.7.11 into cargo workspace and its upgrades its dependencies in cargo.lock and test_postgres_bytea, test_postgres_datestyle, test_postgres_timezone starts failing. I was able to resolve this problem by pinning tokio postgres to an older version.

upgrade postgres-types from 0.26 to 0.27 and postgres-protocol  from 0.66 -> 0.67
or just ran `cargo generate-lockfile`
and then
go to `tests-integration` folder and run `cargo test test_postgres_bytea`

### What did you expect to see?

tests passes

### What did you see instead?

test failures due to getrow function hit unreachable macro
```
    let get_row = |mess: Vec<SimpleQueryMessage>| -> String {
        match &mess[0] {
            SimpleQueryMessage::Row(row) => row.get(0).unwrap().to_string(),
            _ => unreachable!(),
        }
    };
```
I believe simplequerymessage enum is edited with a new [variant RowDescription](https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/lib.rs#L242:L254) and those test failure are due to the result is actually RowDescription.

### What operating system did you use?

macos

### What version of GreptimeDB did you use?

lastest main

### Relevant log output and stack trace

```bash
024-08-05T01:44:02.688714Z DEBUG read_from_region: mito2::read::merge: Merge reader finished, metrics: Metrics { scan_cost: 1.522ms, num_fetch_by_batches: 1, num_fetch_by_rows: 0, num_input_rows: 1, num_output_rows: 1, fetch_cost: 1.413209ms }
2024-08-05T01:44:02.689183Z DEBUG query::dist_plan::merge_scan: Merge scan stop poll stream, partition: 0, region_id: 4398046511104(1024, 0), poll_duration: 2.500083ms, first_consume: 5.114583ms, do_get_cost: 2.581416ms
2024-08-05T01:44:02.738871Z DEBUG servers::postgres::server: Broken pipe: A Tokio 1.x context was found, but it is being shutdown.
2024-08-05T01:44:02.738890Z DEBUG servers::postgres::server: Broken pipe: A Tokio 1.x context was found, but it is being shutdown.
2024-08-05T01:44:02.738899Z DEBUG servers::postgres::server: Broken pipe: A Tokio 1.x context was found, but it is being shutdown.
2024-08-05T01:44:02.738909Z DEBUG servers::postgres::server: Broken pipe: A Tokio 1.x context was found, but it is being shutdown.
test integration_sql_file_test::test_postgres_bytea ... FAILED

failures:

---- integration_sql_file_test::test_postgres_bytea stdout ----
thread 'integration_sql_file_test::test_postgres_bytea' panicked at tests-integration/tests/sql.rs:474:18:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at tests-integration/tests/sql.rs:461:21:
called `Result::unwrap()` on an `Err` value: ()


failures:
    integration_sql_file_test::test_postgres_bytea
```

**Comment by lyang24** [comment]
could it be a regression from rust-postgres?

**Comment by WenyXu** [comment]
> could it be a regression from rust-postgres?

Yes, I reproduced it after updating rust-postgres to 0.7.11

**Comment by WenyXu** [comment]
The behavior changed after updating the `rust-postgres` to 0.7.11. It returns the `SimpleQueryMessage::RowDescription` instead of `SimpleQueryMessage::Row`. I'll give a PR to fix this.

```
2024-08-05T03:06:15.985485Z  INFO main::sql: mess: [RowDescription([SimpleColumn { name: "ts" }]), Row(SimpleQueryRow { columns: [SimpleColumn { name: "ts" }], body: DataRowBody { storage: b"\0\0\0\x1a1997-12-17 07:37:16.123000", len: 1 }, ranges: [Some(4..30)] }), CommandComplete(1)]
```
