### ISSUE TITLE
sqlness test suite lacks isolation

### ISSUE THREAD

**Issue by v0y4g3r** [GreptimeTeam/greptimedb#4779]
### What type of bug is this?

User Experience

### What subsystems are affected?

Other

### Minimal reproduce step

Inside project root:

```bash
mkdir /tmp/{greptime,metasrv,flownode,demo,export}
sudo chown -R root:root /tmp/{greptime,metasrv,flownode,demo,export}
cargo sqlness
```

### What did you expect to see?

sqlness test cases all pass since we expected that each test uses their own directory like `/tmp/sqlness[...]/

### What did you see instead?

```
metasrv log file at /tmp/sqlnessVeVVks/greptime-sqlness-metasrv.log
Generating metasrv config file in /tmp/sqlnessVeVVks/greptimedb-metasrv/metasrv-1727471462905.toml, full content:
[wal]

provider = "raft_engine"


thread 'main_spawn' panicked at /home/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-appender-0.2.3/src/rolling.rs:154:14:
initializing rolling file appender failed: InitError { context: "failed to create log directory", source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/cmd/src/bin/greptime.rs:86:10:
Couldn't join on the associated thread: Any { .. }
thread 'main' panicked at tests/runner/src/env.rs:289:13:
metasrv doesn't up in 10 seconds, quit.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### What operating system did you use?

NA

### What version of GreptimeDB did you use?

latest

**Comment by v0y4g3r** [comment]
This creates annoying permission issues when a host is shared by multiple users. The first user to run `cargo sqlness` owns the created directories, preventing others from running `cargo sqlness`.

There're two leaked directories:
- while creating metasrv/frontend/datanode/flownode instances, the log output is not specified, so all go to `/tmp/greptimedb`
- those copy to/from cases all share `/tmp/demo` and `/tmp/export` directories.
