### ISSUE TITLE
mito and metasrv have inconsistent behaviors while adding columns

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#5248]
### What type of bug is this?

Data corruption

### What subsystems are affected?

Standalone mode, Distributed Cluster

### Minimal reproduce step

1. Create a table test with column a, ts
2. add columns a, b in a gRPC request, ignore errors
3. add column c, d in a gRPC request
4. insert some rows
5. select rows from the table

### What did you expect to see?

Insert and select success

### What did you see instead?

Insert failed
```
thread 'grpc::test::test_distributed_handle_multi_ddl_request' panicked at tests-integration/src/grpc.rs:94:14:
called `Result::unwrap()` on an `Err` value: 0: Table operation error, at src/frontend/src/instance.rs:276:16
1: Cannot find column by name: Column b not found in table table_created_through_grpc, at /Users/evenyag/codes/greptime/procedure-traits/src/operator/src/req_convert/insert/stmt_to_region.rs:106:18
```

### What operating system did you use?

Unrelated

### What version of GreptimeDB did you use?

0.11.1

### Relevant log output and stack trace

```bash
thread 'grpc::test::test_distributed_handle_multi_ddl_request' panicked at tests-integration/src/grpc.rs:94:14:
called `Result::unwrap()` on an `Err` value: 0: Table operation error, at src/frontend/src/instance.rs:276:16
1: Cannot find column by name: Column b not found in table table_created_through_grpc, at /Users/evenyag/codes/greptime/procedure-traits/src/operator/src/req_convert/insert/stmt_to_region.rs:106:18
```

**Comment by killme2008** [comment]
Do we have a plan to fix it? It's a fatal issue.

**Comment by evenyag** [comment]
> Do we have a plan to fix it? It's a fatal issue.

I'm working at this.
