### ISSUE TITLE
Panic when select the system.information_schema.system_catalog table

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#834]
### What type of bug is this?

Crash

### What subsystems are affected?

Standalone mode, Frontend, Datanode

### What happened?

The server panic if we try to execute `select * from system.information_schema.system_catalog;`

### What operating system did you use?

All

### Relevant log output and stack trace

```bash
2023-01-05T06:59:59.491339Z ERROR common_telemetry::panic_hook: panicked at 'System catalog table does not support scan!', src/catalog/src/system.rs:68:9 backtrace=   0: common_telemetry::panic_hook::set_panic_hook::{{closure}}
             at src/common/telemetry/src/panic_hook.rs:30:25
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2032:9
      std::panicking::rust_panic_with_hook
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:577:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/panicking.rs:64:14
   6: <catalog::system::SystemCatalogTable as table::table::Table>::scan::{{closure}}
             at src/catalog/src/system.rs:68:9
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/future/future.rs:124:9
   8: <table::table::adapter::DfTableProviderAdapter as datafusion::datasource::datasource::TableProvider>::scan::{{closure}}
             at src/table/src/table/adapter.rs:77:65
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/future/future.rs:124:9
  10: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at /home/jkshen/.cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/4917235/datafusion/core/src/physical_plan/planner.rs:488:88
```

### How can we reproduce the bug?

```bash
select * from system.information_schema.system_catalog;
```

**Comment by evenyag** [comment]
Should we allow access to this table? Since the `system_catalog` table stores the encoded catalog entries, which should be invisible to end users.

The catalog manager might need to hide this table. But we should provide some tables like `tables`, `schemas`, or `databases` under the `information_schema`, though their data might derived from the `system_catalog` table.
