### ISSUE TITLE
test_distributed_insert_and_query panicked: Too many open files

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#851]
### What type of bug is this?

Other

### What subsystems are affected?

Frontend

### What happened?

Test failures:
- instance::flight::test::test_distributed_insert_and_query
- instance::prometheus::tests::test_distributed_prometheus_remote_rw

### What operating system did you use?

macOS

### Relevant log output and stack trace

```bash
---- instance::flight::test::test_distributed_insert_and_query stdout ----
thread 'instance::flight::test::test_distributed_insert_and_query' panicked at 'called `Result::unwrap()` on an `Err` value: BuildRuntime { source: Os { code: 24, kind: Uncategorized, message: "Too many open files" }, backtrace: Backtrace(   0: backtrace::backtrace::libunwind::trace
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/capture.rs:140:22
   4: <snafu::backtrace_shim::Backtrace as snafu::GenerateImplicitData>::generate
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.3/src/backtrace_shim.rs:15:19
      snafu::GenerateImplicitData::generate_with_source
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.3/src/lib.rs:1149:9
   5: <common_runtime::error::BuildRuntimeSnafu as snafu::IntoError<common_runtime::error::Error>>::into_error
             at /Users/evenyag/codes/greptime/greptimedb/src/common/runtime/src/error.rs:21:17
   6: <core::result::Result<T,E> as snafu::ResultExt<T,E>>::context
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/snafu-0.7.3/src/lib.rs:694:31
   7: common_runtime::runtime::Builder::build
             at /Users/evenyag/codes/greptime/greptimedb/src/common/runtime/src/runtime.rs:126:23
   8: frontend::tests::create_datanode_client::{{closure}}
             at src/tests.rs:101:9
   9: frontend::tests::create_distributed_instance::{{closure}}
             at src/tests.rs:211:65
  10: frontend::instance::flight::test::test_distributed_insert_and_query::{{closure}}
             at src/instance/flight.rs:305:84
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/future/future.rs:124:9
  12: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/park.rs:283:63
  13: tokio::runtime::coop::with_budget
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:102:5
      tokio::runtime::coop::budget
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:68:5
      tokio::runtime::park::CachedParkThread::block_on
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/park.rs:283:31
  14: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/context.rs:295:13
  15: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  16: tokio::runtime::runtime::Runtime::block_on
             at /Users/evenyag/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/runtime.rs:284:45
  17: frontend::instance::flight::test::test_distributed_insert_and_query
             at src/instance/flight.rs:377:9
  18: frontend::instance::flight::test::test_distributed_insert_and_query::{{closure}}
             at src/instance/flight.rs:301:50
  19: core::ops::function::FnOnce::call_once
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/ops/function.rs:507:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/ops/function.rs:507:5
      test::__rust_begin_short_backtrace
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/test/src/lib.rs:656:18
  21: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2000:9
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panic.rs:137:14
      test::run_test_in_process
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/test/src/lib.rs:679:27
      test::run_test::run_test_inner::{{closure}}
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/test/src/lib.rs:573:39
  22: test::run_test::run_test_inner::{{closure}}
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/test/src/lib.rs:600:37
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:121:18
  23: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/thread/mod.rs:550:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/thread/mod.rs:549:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/ops/function.rs:507:5
  24: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2000:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2000:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys/unix/thread.rs:108:17
  25: __pthread_deallocate
) }', src/frontend/src/tests.rs:105:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How can we reproduce the bug?

```bash
Run `cargo test --workspace`
```

**Comment by evenyag** [comment]
Run `cargo test -p frontend` can also reproduce this.
